<table align="left" width=100%>
    <tr>
        <td width="10%">
            <img src="in_class.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                  <b> Inclass - Lab <br> (Day 1) </b>
                </font>
            </div>
        </td>
    </tr>
</table>

##  Table of Content

1. **[One Dimensional Array](#1D)**
2. **[Two Dimensional Array](#2D)**
3. **[Stacking](#Stacking)**
4. **[Splitting](#Splitting)**
5. **[For Loop](#loop)**

**Import the NumPy library before solving the exercises**

### Let's begin with some hands-on practice exercises

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below: (or create your own list)**<br>

    list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

In [5]:
# type your code here
import numpy as np#alais name as np
list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]
a_array=np.array(list_temperature)
a_array
print(a_array)

[3.04 1.65 5.76 1.66 1.54 4.69 2.68]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

    weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [9]:
# type your code here
weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]
w=np.array(weights)
w[w>68]

array([74.2, 85. , 74. , 70.5, 86. , 82. ])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [19]:
# type your code here
np.random.seed(seed=0)
a=np.random.randint(20,41,10)
print(a)

[32 35 20 23 23 27 29 39 38 24]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a program to get the fifth power of the first five positive integers
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [21]:
# type your code here
v=np.arange(1,6)
v
np.power(v,5)

array([   1,   32,  243, 1024, 3125], dtype=int32)

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to create an array of all the odd integers from 50 to 100 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [25]:
# type your code here
o=np.arange(51,100,2)
o

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85, 87, 89, 91, 93, 95, 97, 99])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below: (or create your own array)**

    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [30]:
# type your code here
A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
print(A)
a = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
print(np.array(a))
print(np.sum(a,axis=0))

[[1, 4, 8], [5, 7, 3], [9, 14, 2]]
[[ 1  4  8]
 [ 5  7  3]
 [ 9 14  2]]
[15 25 13]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a code to get the element-wise remainder of an array after division by 8 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
    
    num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

In [35]:
# type your code here
num = [42, 87, 90, 14, 32, 75, 61, 80, 92]
n=np.array(num)
np.remainder(n,8)#n%8 or np.mod(n,8)

array([2, 7, 2, 6, 0, 3, 5, 0, 4], dtype=int32)

<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [46]:
# type your code here
a_1d=np.arange(1,21)
print(a_1d)
a_2d=a_1d.reshape(2,10)
print(a_2d)
print(a_2d[1,0:5])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[11 12 13 14 15]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a program to find common values between two arrays 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    prices_monday = [10, 30, 50, 60, 90]

    prices_tuesday = [50, 20, 80, 125, 10, 70]

In [50]:
# type your code here
pm=np.array([10, 30, 50, 60, 90])
print(pm)
pt=np.array([50, 20, 80, 125, 10, 70])
print(pt)
np.intersect1d(pm,pt)

[10 30 50 60 90]
[ 50  20  80 125  10  70]


array([10, 50])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to find BMI of the patients whose height and weight is provided in the list given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    list of weights (in kg)
    weights = [57, 69, 54, 65 ,71, 62, 56]

    list of heights (in m)<br>
    heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

In [57]:
# type your code here
w= np.array([57, 69, 54, 65 ,71, 62, 56])
h= np.array([1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53])
print(w)
print(h)
bmi=np.round(w/h**2,3)
print(bmi)

[57 69 54 65 71 62 56]
[1.59 1.75 1.66 1.74 1.64 1.72 1.53]
[22.547 22.531 19.596 21.469 26.398 20.957 23.922]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a program to add a new column ([5,7]) at the last position in the array given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    array1 = [[[3, 4], [8, 2],[5, 9]]]

In [61]:
# type your code here
array1 =np.array([[[3, 4], [8, 2],[5, 9]]])
array_new=np.insert(array1,obj=3,values=[5,7],axis=1)
array_new

array([[[3, 4],
        [8, 2],
        [5, 9],
        [5, 7]]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a code to print the identity matrix of order 5</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [63]:
# type your code here
identity=np.eye(5,dtype=np.int32)
identity

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Write a program to transpose a matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
    M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [75]:
# type your code here
m=np.array([[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]])
print(m)
np.transpose(m) #m.T

[[15 17 45 56]
 [ 7 42 15 63]
 [54  3 61 41]
 [ 0 87 16 20]]


array([[15,  7, 54,  0],
       [17, 42,  3, 87],
       [45, 15, 61, 16],
       [56, 63, 41, 20]])

<a id="Stacking"> </a>
## 3. Stacking

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Write a program to combine the two arrays vertically</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**<br>

    A1 = [[5, 9], [7, 6]]

    A2 = [[8,-7], [0,4]]

Combine the array A2 with A1

In [79]:
# type your code here
A1=np.array([[5, 9], [7, 6]])
print("A1:\n",A1)
A2=np.array([[8,-7], [0,4]])
print("A2:\n",A2)
np.vstack((A1,A2))#print(A2+A1)

A1:
 [[5 9]
 [7 6]]
A2:
 [[ 8 -7]
 [ 0  4]]


array([[ 5,  9],
       [ 7,  6],
       [ 8, -7],
       [ 0,  4]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Write a code to combine the two arrays horizontally</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**

    A1 = [[-81, 75, 40], [27, 67, 52]]

    A2 = [[15, 54], [39, 56]]

Combine the array A2 with A1

In [81]:
# type your code here
A1 =np.array([[-81, 75, 40], [27, 67, 52]])
print("A1:\n",A1)
A2 =np.array([[15, 54], [39, 56]])
print("A2:\n",A2)
np.hstack((A1,A2))

A1:
 [[-81  75  40]
 [ 27  67  52]]
A2:
 [[15 54]
 [39 56]]


array([[-81,  75,  40,  15,  54],
       [ 27,  67,  52,  39,  56]])

<a id="Splitting"> </a>
## 4. Splitting

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Write a code to divide the array into three sub-arrays containing
                       equal number of rows</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]

In [88]:
# type your code here
A =np.array([[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]])
print("A:\n",A)
a=np.vsplit(A,3)
a

A:
 [[ 4  7]
 [ 2 -3]
 [ 8  1]
 [ 0  9]
 [ 5 -1]
 [ 8  3]]


[array([[ 4,  7],
        [ 2, -3]]), array([[8, 1],
        [0, 9]]), array([[ 5, -1],
        [ 8,  3]])]

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Write a program to divide the array into two sub-arrays containing equal number of columns
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [94]:
# type your code here
B =np.array([[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]])
print(B.shape)
np.hsplit(B, 2)


(3, 4)


[array([[ 8,  7],
        [ 2, -3],
        [ 8,  5]]), array([[ 0,  9],
        [ 5, 10],
        [-1,  3]])]

<a id="loop"> </a>
## 5. For Loop

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>18. Write a program to perform one-to-one mapping of the two lists</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below: (or create your own lists)**<br>

    L1 = [45, 67, 56, 71, 54, 62, 56]

    L2 = [21, 52, 64, 10, 49, 74, 26]

In [1]:
# type your code here
L1 = [45, 67, 56, 71, 54, 62, 56]

L2 = [21, 52, 64, 10, 49, 74, 26]
print(list(zip(L1,L2)))

for i,j in zip(L1,L2):
    print(i,j)

[(45, 21), (67, 52), (56, 64), (71, 10), (54, 49), (62, 74), (56, 26)]
45 21
67 52
56 64
71 10
54 49
62 74
56 26


In [109]:
L1 = [45, 67, 56, 71, 54, 62, 56]
L2 = [21, 52, 64, 10, 49, 74, 26]
list(zip(L1,L2))

[(45, 21), (67, 52), (56, 64), (71, 10), (54, 49), (62, 74), (56, 26)]

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>19. Define a for loop to apply the function (2x-1)/(x+5) on every element of an array </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**
    
    numbers = [6, 5, 3, 15]

In [100]:
# type your code here
numbers=np.array([6, 5, 3, 15])
for x in numbers:
    print((2*x-1)/(x+5))

1.0
0.9
0.625
1.45


In [101]:
(2*numbers-1)/(numbers+5)

array([1.   , 0.9  , 0.625, 1.45 ])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>20. Create an identity matrix with n dimensions (take input from the user). Fill the diagonals of that matrix with the multiples of the number provided by the user; take another input from the user. Consider the output below as an example </b>
                </font>
            </div>
        </td>
    </tr>
</table>

<table align="center">
    <td height = '100', width = '700'>
          <img src="que 20.png">
        </td>
</table>

In [106]:
# type your code here
dim = int(input("Enter the dimensions: "))

multiple = int(input("Enter the multiplies: "))

a = np.identity(dim)

for i,j in zip(reversed(range(dim)),range(dim)):
    
    a[j][j] = (j+1)*multiple
    
    a[i][j] = (j+1)*multiple
    
print(a)

Enter the dimensions: 4
Enter the multiplies: 6
[[ 6.  0.  0. 24.]
 [ 0. 12. 18.  0.]
 [ 0. 12. 18.  0.]
 [ 6.  0.  0. 24.]]
