# NPV DAY1 23-08-2021

# PANDAS-NUMPY(NUMERICAL PYTHON)-MATPLOTLIB-SEABORN

#### NUMPY IS THE CORE LIBRARY FOR SCIENTIFIC COMPUTING IN PYTHON.NUMPY IS GENERAL PURPOSE ARRAY(HOMOGENOUS BUT IN PYTHON-HETROGENEOUS) PROCESS PACKAGE-PERFORMS HIGH PERFORMANCE MULTIDEMENSIONAL ARRAY OBJECT AND TOOLS FOR WORKING WITH THESE ARRAY

#### more powerful than pandas because of more libarary function but not beautiful to view

#### conversion of numpy to pandas and pandas to numpy is easy

#### ARRAY-COVERS N DIMENSIONAL AND THEY ARE ITERABLE

##### 1D ARRAY-SERIES

###### shape(4,)-LOOK LIKE TUPPLE

##### 2D ARRAY-DATA FRAME

###### shape(2,3)
###### AXIS 0-ROWS
###### AXIS 1-COLUMN

##### 3D ARRAY

###### shape(4,3,2)
###### AXIS 0-ROWS,AXIS 1,AXIS2

In [1]:
import numpy as np

#### CREATION OF 1D,2D

In [16]:
mylist1=[1,2,3,4,5]
n1=np.array(mylist1)
n1

array([1, 2, 3, 4, 5])

In [4]:
print(type(n1))

<class 'numpy.ndarray'>


In [5]:
n1.ndim

1

In [6]:
print(n1.ndim)

1


In [7]:
print(n1.shape) #counts tuple of elements along each axis

(5,)


In [8]:
print(n1.dtype) #type of bits of each elements in the array

int32


In [10]:
print(n1.size) #total elements in array

5


In [12]:
print(n1.itemsize) #size in bytes of each elements in the array

4


In [15]:
n2=np.array(mylist1,dtype=np.int8) #donot force a dtype
n2

array([1, 2, 3, 4, 5], dtype=int8)

In [22]:
mylist1=[1,2,3,4,5]
n1=np.array(mylist1)
n1
print(type(n1))
print(n1.ndim)
print(n1.shape)
print(n1.dtype)
print(n1.size)
print(n1.itemsize)

<class 'numpy.ndarray'>
1
(5,)
int32
5
4


In [24]:
mylist2=[1,2,3.89,4,5]
n3=np.array(mylist2)
n3
print(type(n3))
print(n3.ndim)
print(n3.shape)
print(n3.dtype)
print(n3.size)
print(n3.itemsize)

<class 'numpy.ndarray'>
1
(5,)
float64
5
8


In [21]:
print(n3.dtype)

float64


##### 2D ARRAY

In [25]:
mylist3=[[5,3,4],[9,0,0]]
print(mylist3)

n3=np.array(mylist3)
print(n3)
print(type(n3))
print(n3.ndim)
print(n3.shape)
print(n3.dtype)
print(n3.size)
print(n3.itemsize)

[[5, 3, 4], [9, 0, 0]]
[[5 3 4]
 [9 0 0]]
<class 'numpy.ndarray'>
2
(2, 3)
int32
6
4


###### 2D FLOAT

In [26]:
mylist3=[[5.2,3.0,4.5],[9.1,0.2,0.3]]
print(mylist3)

n3=np.array(mylist3)
print(n3)
print(type(n3))
print(n3.ndim)
print(n3.shape)
print(n3.dtype)
print(n3.size)
print(n3.itemsize)

[[5.2, 3.0, 4.5], [9.1, 0.2, 0.3]]
[[5.2 3.  4.5]
 [9.1 0.2 0.3]]
<class 'numpy.ndarray'>
2
(2, 3)
float64
6
8


###### 2D-COMPLEX

In [27]:
mylist3=[[5+6j,3,4],[9,0,0]]
print(mylist3)

n3=np.array(mylist3)
print(n3)
print(type(n3))
print(n3.ndim)
print(n3.shape)
print(n3.dtype)
print(n3.size)
print(n3.itemsize)

[[(5+6j), 3, 4], [9, 0, 0]]
[[5.+6.j 3.+0.j 4.+0.j]
 [9.+0.j 0.+0.j 0.+0.j]]
<class 'numpy.ndarray'>
2
(2, 3)
complex128
6
16


## USING RANGE-1D,2D

In [29]:
n1=np.arange(20)
print(n1.shape)
n1

(20,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
n1=np.arange(10,20)
print(n1.shape)
n1

(10,)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
n1=np.arange(10,20,2)
print(n1.shape)
n1

(5,)


array([10, 12, 14, 16, 18])

In [32]:
n1=np.arange(1.1,3.9,0.25) #numpy arange can be float
print(n1.shape)
n1

(12,)


array([1.1 , 1.35, 1.6 , 1.85, 2.1 , 2.35, 2.6 , 2.85, 3.1 , 3.35, 3.6 ,
       3.85])

## USING RANGE-2D

In [40]:
n34=np.arange(12)
print(n34.shape)
n34

(12,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
n34=np.arange(12).reshape(3,4)
print(n34.shape)
n34

(3, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
n34=np.arange(12).reshape(2,6)
print(n34.shape)
n34

(2, 6)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [46]:
n34=np.arange(12).reshape(1,12)
print(n34.shape)
n34

(1, 12)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [48]:
n34=np.arange(12).reshape(4,-1) # -1 is instuction to calculate that dim internally/automatically
print(n34.shape)
n34

(4, 3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [1]:
import numpy as np
n34=np.arange(12).reshape(-1,4) # -1 is instuction to calculate that dim internally/automatically
print(n34.shape)
n34

(3, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
n34=np.arange(12).reshape(-1,-1) # -1,-1 can not give -1,-1 at the same time as instuction to calculate that dim automatically
print(n34.shape)
n34

ValueError: can only specify one unknown dimension

In [50]:
n34=np.arange(12).reshape(-1,6) # -1 is instuction to calculate that dim automatically
print(n34.shape)
n34

(2, 6)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

## 1D-RANDOM VALUES

In [51]:
n10=np.random.randint(low=10,high=100,size=(10,))
print(n10.shape)
n10

(10,)


array([27, 46, 98, 65, 65, 30, 21, 31, 43, 56])

In [52]:
np.random.seed(23) #pseudo random number generator build in the system-
n10=np.random.randint(low=10,high=100,size=(10,))
print(n10.shape)
n10

(10,)


array([93, 50, 83, 64, 41, 86, 49, 35, 61, 16])

## 2D RANDOM VALUES

In [53]:
np.random.seed(23) #pseudo random number generator build in the system-
n10=np.random.randint(low=10,high=100,size=(3,4))
print(n10.shape)
n10

(3, 4)


array([[93, 50, 83, 64],
       [41, 86, 49, 35],
       [61, 16, 55, 22]])

### FLOAT 

In [54]:
np.random.seed(23) #pseudo random number generator build in the system-
n10=np.random.rand(3,4)#uniform dist framework
print(n10.shape)
n10

(3, 4)


array([[0.51729788, 0.9469626 , 0.76545976, 0.28239584],
       [0.22104536, 0.68622209, 0.1671392 , 0.39244247],
       [0.61805235, 0.41193009, 0.00246488, 0.88403218]])

In [56]:
np.random.seed(23) #pseudo random number generator build in the system-
n10=np.random.randn(3,4)#normal dist framework-BELL CURVE
print(n10.shape)
n10

(3, 4)


array([[ 0.66698806,  0.02581308, -0.77761941,  0.94863382],
       [ 0.70167179, -1.05108156, -0.36754812, -1.13745969],
       [-1.32214752,  1.77225828, -0.34745899,  0.67014016]])

In [57]:
np.random.seed(23) #pseudo random number generator build in the system-
n10=np.random.rand(3,4)#uniform distribution framework i.e 0 to 1
print(n10.shape)
print(n10)
print(n10.min())
print(n10.max())
print(n10.mean())


(3, 4)
[[0.51729788 0.9469626  0.76545976 0.28239584]
 [0.22104536 0.68622209 0.1671392  0.39244247]
 [0.61805235 0.41193009 0.00246488 0.88403218]]
0.002464881200886171
0.9469626038148141
0.4912870595645145


In [58]:
np.random.seed(23) #pseudo random number generator build in the system-
n10=np.random.randn(3,4)#normal distribution framework-BELL CURVE i.e -1 to 1 mean tends to be 0
print(n10.shape)
print(n10)
print(n10.min())
print(n10.max())
print(n10.mean())


(3, 4)
[[ 0.66698806  0.02581308 -0.77761941  0.94863382]
 [ 0.70167179 -1.05108156 -0.36754812 -1.13745969]
 [-1.32214752  1.77225828 -0.34745899  0.67014016]]
-1.3221475225908594
1.7722582783074305
-0.01815084181558928


In [59]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
np.identity(3,dtype=np.int32)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [62]:
np.zeros(shape=(3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
np.ones(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [64]:
np.full(shape=(3,4),fill_value=55)

array([[55, 55, 55, 55],
       [55, 55, 55, 55],
       [55, 55, 55, 55]])

In [65]:
np.empty(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [67]:
empmat=[]
for i in range(10):
    empmat.append(np.empty(shape=(3,4)))
print()
empmat

[array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]), array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]), array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]), array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), array([[4.17706815e+199, 7.26607065e+223, 9.10016856e+276,
         1.27921601e-152],
        [5.30450576e+006, 1.69042031e+195, 6.06117652e+097,
         4.70100449e+180],
        [1.87673453e-152, 2.72306853e-153, 1.66037154e+243,
         1.76243998e+156]]), array([[1.14199446e+243, 1.29314588e+098, 4.70100449e+180,
         1.87673453e-152],
        [9.81925446e+025, 2.31431106e+251, 2.02799178e+267,
         2.35290217e+251],
        [6.57948823e-085, 3.30164407e+180, 3.81431017e+228,
         1.39806874e-152]]), array([[9.28732492e-312, 3.16202013e-322, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 2.14622215e+184, 3.43770312e+179,
         2.67

In [69]:
## 8 bit=255
print(2**8)
print(2**32)
print(2**64)

256
4294967296
18446744073709551616


### ACCESSING A MATRIX

In [70]:
np.random.seed(23)
n89=np.random.randint(low=10,high=100,size=(8,9))
n89

array([[93, 50, 83, 64, 41, 86, 49, 35, 61],
       [16, 55, 22, 59, 76, 85, 95, 79, 74],
       [22, 31, 58, 51, 89, 72, 67, 29, 43],
       [69, 49, 25, 46, 75, 11, 53, 25, 96],
       [93, 68, 35, 76, 84, 45, 66, 23, 70],
       [32, 48, 41, 88, 10, 31, 16, 42, 42],
       [24, 41, 88, 93, 90, 80, 76, 92, 95],
       [65, 37, 72, 53, 84, 81, 52, 93, 31]])

In [111]:
np.random.seed(23)
n89=np.random.randint(low=10,high=100,size=(8,9))
n89

array([[93, 50, 83, 64, 41, 86, 49, 35, 61],
       [16, 55, 22, 59, 76, 85, 95, 79, 74],
       [22, 31, 58, 51, 89, 72, 67, 29, 43],
       [69, 49, 25, 46, 75, 11, 53, 25, 96],
       [93, 68, 35, 76, 84, 45, 66, 23, 70],
       [32, 48, 41, 88, 10, 31, 16, 42, 42],
       [24, 41, 88, 93, 90, 80, 76, 92, 95],
       [65, 37, 72, 53, 84, 81, 52, 93, 31]])

In [112]:
n89[0] #n89[row-index]

array([93, 50, 83, 64, 41, 86, 49, 35, 61])

In [72]:
n89[1]

array([16, 55, 22, 59, 76, 85, 95, 79, 74])

In [73]:
n89[-1]

array([65, 37, 72, 53, 84, 81, 52, 93, 31])

In [114]:
n89[0,0]#n89[row-index,col-index]


93

In [89]:
n89[0,1]#n89[row-index,col-index]


50

In [90]:
n89[0,-1]#n89[row-index,col-index]


61

In [113]:
np.random.seed(23)
n89=np.random.randint(low=10,high=100,size=(8,9))
n89

array([[93, 50, 83, 64, 41, 86, 49, 35, 61],
       [16, 55, 22, 59, 76, 85, 95, 79, 74],
       [22, 31, 58, 51, 89, 72, 67, 29, 43],
       [69, 49, 25, 46, 75, 11, 53, 25, 96],
       [93, 68, 35, 76, 84, 45, 66, 23, 70],
       [32, 48, 41, 88, 10, 31, 16, 42, 42],
       [24, 41, 88, 93, 90, 80, 76, 92, 95],
       [65, 37, 72, 53, 84, 81, 52, 93, 31]])

In [91]:
n89[2:5]#n89[row_slice]

array([[22, 31, 58, 51, 89, 72, 67, 29, 43],
       [69, 49, 25, 46, 75, 11, 53, 25, 96],
       [93, 68, 35, 76, 84, 45, 66, 23, 70]])

In [92]:
n89[2:7:2]#n89[row_slice] with step count

array([[22, 31, 58, 51, 89, 72, 67, 29, 43],
       [93, 68, 35, 76, 84, 45, 66, 23, 70],
       [24, 41, 88, 93, 90, 80, 76, 92, 95]])

In [93]:
n89[3:6]#n89[row_slice]

array([[69, 49, 25, 46, 75, 11, 53, 25, 96],
       [93, 68, 35, 76, 84, 45, 66, 23, 70],
       [32, 48, 41, 88, 10, 31, 16, 42, 42]])

In [94]:
n89[3:6]

array([[69, 49, 25, 46, 75, 11, 53, 25, 96],
       [93, 68, 35, 76, 84, 45, 66, 23, 70],
       [32, 48, 41, 88, 10, 31, 16, 42, 42]])

In [81]:
n89[ 3:6,2:8     ]#n89[row_slice,col_slice]

array([[25, 46, 75, 11, 53, 25],
       [35, 76, 84, 45, 66, 23],
       [41, 88, 10, 31, 16, 42]])

In [82]:
n89[[0,2,-2,-1]] #vectors #n89[list of row indices]

array([[93, 50, 83, 64, 41, 86, 49, 35, 61],
       [22, 31, 58, 51, 89, 72, 67, 29, 43],
       [24, 41, 88, 93, 90, 80, 76, 92, 95],
       [65, 37, 72, 53, 84, 81, 52, 93, 31]])

In [97]:
n89[[0,2,-2,-1]]#n89[list of row indices]

array([[93, 50, 83, 64, 41, 86, 49, 35, 61],
       [22, 31, 58, 51, 89, 72, 67, 29, 43],
       [24, 41, 88, 93, 90, 80, 76, 92, 95],
       [65, 37, 72, 53, 84, 81, 52, 93, 31]])

In [84]:
n89[[0,1,-2,-1],[0,1,-2,-1]] #vector with vector i.e [0][0],[1][1],[-2][-2],[-1][-1] like a zip #n89[[list of row indices],[list of col indices]]

array([93, 55, 92, 31])

In [110]:
list(zip([0,1,-2,-1],[0,1,-2,-1]))#values at the zip coordinates of row list and column list

[(0, 0), (1, 1), (-2, -2), (-1, -1)]

In [85]:
n89[:,4]#n89[list of row indices],[list of col indices]

array([41, 76, 89, 75, 84, 10, 90, 84])

In [105]:
n89[:,4:6]

array([[41, 86],
       [76, 85],
       [89, 72],
       [75, 11],
       [84, 45],
       [10, 31],
       [90, 80],
       [84, 81]])

In [86]:
n89[:,[1,4,6]]

array([[50, 41, 49],
       [55, 76, 95],
       [31, 89, 67],
       [49, 75, 53],
       [68, 84, 66],
       [48, 10, 16],
       [41, 90, 76],
       [37, 84, 52]])

In [87]:
n89[1:6:2,[1,3,-1]]

array([[55, 59, 74],
       [49, 46, 96],
       [48, 88, 42]])

In [98]:
n89[3:2]

array([], shape=(0, 9), dtype=int32)

In [99]:
n89[3:2:-1]

array([[69, 49, 25, 46, 75, 11, 53, 25, 96]])

In [101]:
mylist=list('pythonworld')
mylist

['p', 'y', 't', 'h', 'o', 'n', 'w', 'o', 'r', 'l', 'd']

In [102]:
mylist[2:5]

['t', 'h', 'o']

#### CONDITIONAL ACESS

In [117]:
mask=n89>75

In [119]:
mask

array([[ True, False,  True, False, False,  True, False, False, False],
       [False, False, False, False,  True,  True,  True,  True, False],
       [False, False, False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True],
       [ True, False, False,  True,  True, False, False, False, False],
       [False, False, False,  True, False, False, False, False, False],
       [False, False,  True,  True,  True,  True,  True,  True,  True],
       [False, False, False, False,  True,  True, False,  True, False]])

In [118]:
n89[mask]

array([93, 83, 86, 76, 85, 95, 79, 89, 96, 93, 76, 84, 88, 88, 93, 90, 80,
       76, 92, 95, 84, 81, 93])

In [122]:
n89[n89>75]

array([93, 83, 86, 76, 85, 95, 79, 89, 96, 93, 76, 84, 88, 88, 93, 90, 80,
       76, 92, 95, 84, 81, 93])

In [120]:
n89[np.logical_and(n89>50,n89%2==0)]

array([64, 86, 76, 74, 58, 72, 96, 68, 76, 84, 66, 70, 88, 88, 90, 80, 76,
       92, 72, 84, 52])

In [121]:
n89[np.logical_and(n89>50,1)]

array([93, 83, 64, 86, 61, 55, 59, 76, 85, 95, 79, 74, 58, 51, 89, 72, 67,
       69, 75, 53, 96, 93, 68, 76, 84, 66, 70, 88, 88, 93, 90, 80, 76, 92,
       95, 65, 72, 53, 84, 81, 52, 93])

### MUTABILITY-NUMPY OBJECTS ARE MUTABLE I.E WE CAN UPDATE

In [135]:
n89[2]=888
n89

array([[   1,  667,  667,  667,  667,  667,  667,  667,  667],
       [  16,   55,   22, 1000, 1001, 1002,   95,   79,   74],
       [ 888,  888,  888,  888,  888,  888,  888,  888,  888],
       [  69,   49,   25, 1006, 1007, 1008,   53,   25,   96],
       [  93,   68,   35,   76,   84,   45,   66,   23,   70],
       [  32,   48,   41,   88,   10,   31,   16,   42,   42],
       [ 667,  667,  667,  667,  667,  667,  667,  667,  667],
       [ 667,  667,  667,  667,  667,  667,  667,  667,    3]])

In [136]:
n89[0]

array([  1, 667, 667, 667, 667, 667, 667, 667, 667])

In [138]:
n89[1:4,3:6]=5656
n89

array([[   1,  667,  667,  667,  667,  667,  667,  667,  667],
       [  16,   55,   22, 5656, 5656, 5656,   95,   79,   74],
       [ 888,  888,  888, 5656, 5656, 5656,  888,  888,  888],
       [  69,   49,   25, 5656, 5656, 5656,   53,   25,   96],
       [  93,   68,   35,   76,   84,   45,   66,   23,   70],
       [  32,   48,   41,   88,   10,   31,   16,   42,   42],
       [ 667,  667,  667,  667,  667,  667,  667,  667,  667],
       [ 667,  667,  667,  667,  667,  667,  667,  667,    3]])

In [125]:
n89[[0,-2,-1]]=667
n89

array([[667, 667, 667, 667, 667, 667, 667, 667, 667],
       [ 16,  55,  22,  59,  76,  85,  95,  79,  74],
       [888, 888, 888, 888, 888, 888, 888, 888, 888],
       [ 69,  49,  25,  46,  75,  11,  53,  25,  96],
       [ 93,  68,  35,  76,  84,  45,  66,  23,  70],
       [ 32,  48,  41,  88,  10,  31,  16,  42,  42],
       [667, 667, 667, 667, 667, 667, 667, 667, 667],
       [667, 667, 667, 667, 667, 667, 667, 667, 667]])

In [ ]:

n89[[0,-2,-1]]=np.random.randint(low=10,high=100,size=(3,9))
n89

In [127]:
n89[1:4,3:6]=5656
n89

array([[ 667,  667,  667,  667,  667,  667,  667,  667,  667],
       [  16,   55,   22, 5656, 5656, 5656,   95,   79,   74],
       [ 888,  888,  888, 5656, 5656, 5656,  888,  888,  888],
       [  69,   49,   25, 5656, 5656, 5656,   53,   25,   96],
       [  93,   68,   35,   76,   84,   45,   66,   23,   70],
       [  32,   48,   41,   88,   10,   31,   16,   42,   42],
       [ 667,  667,  667,  667,  667,  667,  667,  667,  667],
       [ 667,  667,  667,  667,  667,  667,  667,  667,  667]])

In [131]:
np.random.seed(23)
n89[1:4,3:6]=np.arange(1000,1009).reshape(3,3)
n89

array([[ 667,  667,  667,  667,  667,  667,  667,  667,  667],
       [  16,   55,   22, 1000, 1001, 1002,   95,   79,   74],
       [ 888,  888,  888, 1003, 1004, 1005,  888,  888,  888],
       [  69,   49,   25, 1006, 1007, 1008,   53,   25,   96],
       [  93,   68,   35,   76,   84,   45,   66,   23,   70],
       [  32,   48,   41,   88,   10,   31,   16,   42,   42],
       [ 667,  667,  667,  667,  667,  667,  667,  667,  667],
       [ 667,  667,  667,  667,  667,  667,  667,  667,  667]])

In [132]:
n89[[0,0,-1,-1],[0,0,-1,-1]]


array([667, 667, 667, 667])

In [134]:
n89[[0,0,-1,-1],[0,0,-1,-1]]=np.arange(4)
n89

array([[   1,  667,  667,  667,  667,  667,  667,  667,  667],
       [  16,   55,   22, 1000, 1001, 1002,   95,   79,   74],
       [ 888,  888,  888, 1003, 1004, 1005,  888,  888,  888],
       [  69,   49,   25, 1006, 1007, 1008,   53,   25,   96],
       [  93,   68,   35,   76,   84,   45,   66,   23,   70],
       [  32,   48,   41,   88,   10,   31,   16,   42,   42],
       [ 667,  667,  667,  667,  667,  667,  667,  667,  667],
       [ 667,  667,  667,  667,  667,  667,  667,  667,    3]])

### ARITHMETIC OPERATIONS

In [139]:
n1=np.arange(10)
n2=np.arange(100,110)
print(n1)
print(n2)

[0 1 2 3 4 5 6 7 8 9]
[100 101 102 103 104 105 106 107 108 109]


In [140]:
n1+n2

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118])

In [ ]:
n34a

In [ ]:
n34a-n34b

In [ ]:
n34a*n34b

In [ ]:
n34a+n34b

In [141]:
111*11

1221

In [ ]:
## m,n@n,k

### COMPARING LIST OPERATION WITH NUMPY

In [143]:
mylist1=list(range(10000))
mylist2=list(range(10000))

In [144]:
mylist3=[mylist1[i]+mylist2[i] for i in range(10000)]
print(len(mylist3))

10000


In [146]:
import time

In [150]:
size=500000
mylist1=list(range(10000))
mylist2=list(range(10000))

st=time.time()

mylist3=[mylist1[i]+mylist2[i] for i in range(10000)]
et=time.time()
print(len(mylist3))


print('time taken',et-st)

print(len(mylist3))





10000
time taken 0.0
10000


In [152]:
size=500000
mylist1=list(range(10000))
mylist2=list(range(10000))

n1=np.array(mylist1)
n2=np.array(mylist2)
st=time.time()
n3=n1+n2
et=time.time()
print('np time taken',et-st)


np time taken 0.0


In [153]:
size=500000
mylist1=list(range(10000))
mylist2=list(range(10000))

st=time.time()

mylist3=[mylist1[i]+mylist2[i] for i in range(10000)]
et=time.time()
print(len(mylist3))


print('time taken',et-st)

print(len(mylist3))




n1=np.array(mylist1)
n2=np.array(mylist2)
st=time.time()
n3=n1+n2
et=time.time()
print('np time taken',et-st)


10000
time taken 0.0
10000
np time taken 0.0


## BROADCASTING

#### SCALAR BROADCASTING

In [154]:
n34=np.arange(12).reshape(3,4)
n34

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [155]:
n34+100 #100 is added to every element 100 is a scalar value is added-SCALAR BROADCASTING

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

In [156]:
n31=np.arange(1000,1003).reshape(3,1)
n31

array([[1000],
       [1001],
       [1002]])

In [157]:
n34

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [158]:
n34+n31 #axis 1 broadcasting or streching

array([[1000, 1001, 1002, 1003],
       [1005, 1006, 1007, 1008],
       [1010, 1011, 1012, 1013]])

In [166]:
n34.shape

(3, 4)

In [161]:
n14=np.arange(2000,2004).reshape(1,4)
n14

array([[2000, 2001, 2002, 2003]])

In [162]:
n34+n14

array([[2000, 2002, 2004, 2006],
       [2004, 2006, 2008, 2010],
       [2008, 2010, 2012, 2014]])

In [167]:
n13=np.arange(100,103).reshape(1,3)
n41=np.arange(200,204).reshape(4,1)

print(n13)
print()
print(n41)

[[100 101 102]]

[[200]
 [201]
 [202]
 [203]]


In [168]:
n13+n41 #both axis streching or broadcasting

array([[300, 301, 302],
       [301, 302, 303],
       [302, 303, 304],
       [303, 304, 305]])

## 2D STACKING

In [170]:
n23=np.arange(6).reshape(2,3)
n23

array([[0, 1, 2],
       [3, 4, 5]])

In [171]:
n43=np.arange(100,112).reshape(4,3)
n43

array([[100, 101, 102],
       [103, 104, 105],
       [106, 107, 108],
       [109, 110, 111]])

### VSTACK

In [173]:
n=np.vstack((n23,n43))
print(n.shape)
n

(6, 3)


array([[  0,   1,   2],
       [  3,   4,   5],
       [100, 101, 102],
       [103, 104, 105],
       [106, 107, 108],
       [109, 110, 111]])

In [188]:
n=np.vstack(tup=(n23,n43))
print(n.shape)
n

(6, 3)


array([[  0,   1,   2],
       [  3,   4,   5],
       [100, 101, 102],
       [103, 104, 105],
       [106, 107, 108],
       [109, 110, 111]])

In [174]:
n34=np.arange(12).reshape(3,4)
n36=np.arange(100,118).reshape(3,6)

In [175]:
n34

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [176]:
n36

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117]])

### HSTACK

In [181]:
a=np.hstack((n34,n36))
print(a.shape)
n

(3, 10)


array([[  0,   1,   2],
       [  3,   4,   5],
       [100, 101, 102],
       [103, 104, 105],
       [106, 107, 108],
       [109, 110, 111]])

In [189]:
a=np.hstack(tup=(n34,n36))
print(a.shape)
n

(3, 10)


array([[  0,   1,   2],
       [  3,   4,   5],
       [100, 101, 102],
       [103, 104, 105],
       [106, 107, 108],
       [109, 110, 111]])

### COLUM_STACK

In [183]:
n1=np.array([10,11,12,13])
n2=np.array([110,111,112,113])

In [184]:
n1

array([10, 11, 12, 13])

In [185]:
n2

array([110, 111, 112, 113])

In [186]:
np.column_stack(tup=(n1,n2))

array([[ 10, 110],
       [ 11, 111],
       [ 12, 112],
       [ 13, 113]])

### ROW STACK

In [187]:
np.row_stack(tup=(n1,n2))

array([[ 10,  11,  12,  13],
       [110, 111, 112, 113]])

## SPLITTING

In [190]:
n8_12=np.arange(96).reshape(8,12)
n8_12

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
       [84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]])

## EVEN SPLITTING-VSPLIT,HSPLIT

### VSPLIT

In [192]:
n=np.vsplit(n8_12,4)
print(type(n))

<class 'list'>


In [200]:
for item in n:
    print(item)
    print(type(item))
    print(item.shape)
    print()

[[ 0  1  2]
 [12 13 14]
 [24 25 26]
 [36 37 38]
 [48 49 50]
 [60 61 62]
 [72 73 74]
 [84 85 86]]
<class 'numpy.ndarray'>
(8, 3)

[[ 3  4]
 [15 16]
 [27 28]
 [39 40]
 [51 52]
 [63 64]
 [75 76]
 [87 88]]
<class 'numpy.ndarray'>
(8, 2)

[[ 5]
 [17]
 [29]
 [41]
 [53]
 [65]
 [77]
 [89]]
<class 'numpy.ndarray'>
(8, 1)

[[ 6  7  8]
 [18 19 20]
 [30 31 32]
 [42 43 44]
 [54 55 56]
 [66 67 68]
 [78 79 80]
 [90 91 92]]
<class 'numpy.ndarray'>
(8, 3)

[[ 9 10]
 [21 22]
 [33 34]
 [45 46]
 [57 58]
 [69 70]
 [81 82]
 [93 94]]
<class 'numpy.ndarray'>
(8, 2)

[[11]
 [23]
 [35]
 [47]
 [59]
 [71]
 [83]
 [95]]
<class 'numpy.ndarray'>
(8, 1)



In [194]:
n=np.vsplit(n8_12,2)
print(n[0].shape)
n[0]

(4, 12)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

### HSPLIT

In [196]:
n=np.hsplit(n8_12,2)
print(n[0].shape)
n[0]

(8, 6)


array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29],
       [36, 37, 38, 39, 40, 41],
       [48, 49, 50, 51, 52, 53],
       [60, 61, 62, 63, 64, 65],
       [72, 73, 74, 75, 76, 77],
       [84, 85, 86, 87, 88, 89]])

In [195]:
n=np.hsplit(n8_12,3)
print(n[0].shape)
n[0]

(8, 4)


array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [24, 25, 26, 27],
       [36, 37, 38, 39],
       [48, 49, 50, 51],
       [60, 61, 62, 63],
       [72, 73, 74, 75],
       [84, 85, 86, 87]])

## UNEVEN SPLITTING

In [197]:
n8_12

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
       [84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]])

In [198]:
n=np.hsplit(n8_12,[3,5,6,9,11]) #:356911
len(n)

6

In [199]:
for item in n:
    print(item)
    print(type(item))
    print(item.shape)
    print()

[[ 0  1  2]
 [12 13 14]
 [24 25 26]
 [36 37 38]
 [48 49 50]
 [60 61 62]
 [72 73 74]
 [84 85 86]]
<class 'numpy.ndarray'>
(8, 3)

[[ 3  4]
 [15 16]
 [27 28]
 [39 40]
 [51 52]
 [63 64]
 [75 76]
 [87 88]]
<class 'numpy.ndarray'>
(8, 2)

[[ 5]
 [17]
 [29]
 [41]
 [53]
 [65]
 [77]
 [89]]
<class 'numpy.ndarray'>
(8, 1)

[[ 6  7  8]
 [18 19 20]
 [30 31 32]
 [42 43 44]
 [54 55 56]
 [66 67 68]
 [78 79 80]
 [90 91 92]]
<class 'numpy.ndarray'>
(8, 3)

[[ 9 10]
 [21 22]
 [33 34]
 [45 46]
 [57 58]
 [69 70]
 [81 82]
 [93 94]]
<class 'numpy.ndarray'>
(8, 2)

[[11]
 [23]
 [35]
 [47]
 [59]
 [71]
 [83]
 [95]]
<class 'numpy.ndarray'>
(8, 1)



In [204]:
n1=np.hsplit(n8_12,[2,5,6,7,10]) #:2:5:6:7:10
n1

[array([[ 0,  1],
        [12, 13],
        [24, 25],
        [36, 37],
        [48, 49],
        [60, 61],
        [72, 73],
        [84, 85]]), array([[ 2,  3,  4],
        [14, 15, 16],
        [26, 27, 28],
        [38, 39, 40],
        [50, 51, 52],
        [62, 63, 64],
        [74, 75, 76],
        [86, 87, 88]]), array([[ 5],
        [17],
        [29],
        [41],
        [53],
        [65],
        [77],
        [89]]), array([[ 6],
        [18],
        [30],
        [42],
        [54],
        [66],
        [78],
        [90]]), array([[ 7,  8,  9],
        [19, 20, 21],
        [31, 32, 33],
        [43, 44, 45],
        [55, 56, 57],
        [67, 68, 69],
        [79, 80, 81],
        [91, 92, 93]]), array([[10, 11],
        [22, 23],
        [34, 35],
        [46, 47],
        [58, 59],
        [70, 71],
        [82, 83],
        [94, 95]])]

In [201]:
np.vsplit(n8_12,[3,4]) #:3:4

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]]),
 array([[36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]]),
 array([[48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]])]

## AGGREGATION FUNCTIONS(AGGREGATE)-FACTORIAL,SUM,MAX,MIN,MEDIAN

In [205]:
np.random.seed(23)
n34=np.random.randint(low=5,high=45,size=(3,4))
n34

array([[24, 43, 14, 36],
       [17, 32, 44, 31],
       [30, 11, 17,  7]])

In [206]:
np.sum(n34,axis=1)

array([117, 124,  65])

In [207]:
np.sum(n34,axis=None)

306

In [208]:
np.sum(n34,axis=0)

array([71, 86, 75, 74])

In [210]:
print(np.sum(n34,axis=None))
print(np.sum(n34,axis=0))
print(np.sum(n34,axis=1))

306
[71 86 75 74]
[117 124  65]


In [215]:
print(np.mean(n34,axis=None))
print(np.mean(n34,axis=0))
print(np.mean(n34,axis=1))

25.5
[23.66666667 28.66666667 25.         24.66666667]
[29.25 31.   16.25]


In [217]:
print(np.std(n34,axis=None))
print(np.std(n34,axis=0))
print(np.std(n34,axis=1))

11.84271928232701
[ 5.31245915 13.27487183 13.49073756 12.6578917 ]
[11.12148821  9.56556323  8.69985632]


In [218]:
print(np.var(n34,axis=None))
print(np.var(n34,axis=0))
print(np.var(n34,axis=1))

140.25
[ 28.22222222 176.22222222 182.         160.22222222]
[123.6875  91.5     75.6875]


In [219]:
print(np.min(n34,axis=None))
print(np.min(n34,axis=0))
print(np.min(n34,axis=1))

7
[17 11 14  7]
[14 17  7]


## UTILITY FUNCTION

In [220]:
np.linspace(start=0,stop=5000000,num=6)

array([      0., 1000000., 2000000., 3000000., 4000000., 5000000.])

In [223]:
n=np.linspace(start=0,stop=5000000,num=6,retstep=True)
print(n[-1])
n[0]

1000000.0


array([      0., 1000000., 2000000., 3000000., 4000000., 5000000.])

In [225]:
a=np.linspace(start=-1,stop=1,num=5,retstep=True)
print(a[-1])
a[0]

0.5


array([-1. , -0.5,  0. ,  0.5,  1. ])

In [ ]:
#an=a0+(n-1)d

#### log

In [226]:
np.log(1000)

6.907755278982137

In [227]:
np.log10(1000)

3.0

In [228]:
n34

array([[24, 43, 14, 36],
       [17, 32, 44, 31],
       [30, 11, 17,  7]])

In [229]:
np.log(n34)

array([[3.17805383, 3.76120012, 2.63905733, 3.58351894],
       [2.83321334, 3.4657359 , 3.78418963, 3.4339872 ],
       [3.40119738, 2.39789527, 2.83321334, 1.94591015]])

In [230]:
np.log10(n34)

array([[1.38021124, 1.63346846, 1.14612804, 1.5563025 ],
       [1.23044892, 1.50514998, 1.64345268, 1.49136169],
       [1.47712125, 1.04139269, 1.23044892, 0.84509804]])

In [ ]:
n23=np.array([100])

In [231]:
np.e

2.718281828459045

In [234]:
np.exp(2)

7.38905609893065

In [233]:
np.exp(n34)

array([[2.64891221e+10, 4.72783947e+18, 1.20260428e+06, 4.31123155e+15],
       [2.41549528e+07, 7.89629602e+13, 1.28516001e+19, 2.90488497e+13],
       [1.06864746e+13, 5.98741417e+04, 2.41549528e+07, 1.09663316e+03]])

In [232]:
np.e**7

1096.6331584284583

### iterations 

In [238]:
for item in n34:
    print(item)
    print()

[24 43 14 36]

[17 32 44 31]

[30 11 17  7]



In [239]:
for element in np.nditer(n34):
    print(element)

24
43
14
36
17
32
44
31
30
11
17
7


In [241]:
print(n34)
for index,value in np.ndenumerate(n34):
    print(index,value)

[[24 43 14 36]
 [17 32 44 31]
 [30 11 17  7]]
(0, 0) 24
(0, 1) 43
(0, 2) 14
(0, 3) 36
(1, 0) 17
(1, 1) 32
(1, 2) 44
(1, 3) 31
(2, 0) 30
(2, 1) 11
(2, 2) 17
(2, 3) 7


### INSERT

In [242]:
n34

array([[24, 43, 14, 36],
       [17, 32, 44, 31],
       [30, 11, 17,  7]])

#### insert a row 

In [244]:
n=np.insert(n34,1,[0,1,2,3],axis=0)
print(n)

[[24 43 14 36]
 [ 0  1  2  3]
 [17 32 44 31]
 [30 11 17  7]]


In [245]:
n=np.insert(n34,1,999,axis=0)#values take it as broadcasting
print(n)

[[ 24  43  14  36]
 [999 999 999 999]
 [ 17  32  44  31]
 [ 30  11  17   7]]


In [255]:
n34.shape
n34

array([[24, 43, 14, 36],
       [17, 32, 44, 31],
       [30, 11, 17,  7]])

In [248]:
n=np.insert(n34,1,np.arange(8).reshape(2,4),axis=0)
print(n)

[[24 43 14 36]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [17 32 44 31]
 [30 11 17  7]]


In [258]:
n=np.insert(n34,1,np.arange(12).reshape(4,3),axis=1)
print(n)

[[24  0  3  6  9 43 14 36]
 [17  1  4  7 10 32 44 31]
 [30  2  5  8 11 11 17  7]]


## 3D MATRIX

In [259]:
m342=np.arange(24).reshape(3,4,2)
print(m342)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [263]:
mylist342=[[11,31],[12,32],[13,33],[14,34],[15,35],[16,36],[17,37],[18,38],[19,39],[20,40],[21,41],[22,42]
          ]
print(len(mylist342))
.shape

12


AttributeError: 'list' object has no attribute 'shape'

In [ ]:
n342=np.arange(24).reshape(4,3,2)
n342.shape

In [ ]:
n342

In [ ]:
n342[1,2,1]

In [ ]:
n342[1:,1:3,1]

In [264]:
n342a=np.arange(11,23).reshape(3,4)
n342a.shape

(3, 4)

In [265]:
n342a

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [ ]:
n342a=np.arange(11,23).reshape(3,4)
n342a.shape

In [ ]:
n=np.stack(arrays=)

In [1]:
string='Hi,Hello,How Are You?'
string

'Hi,Hello,How Are You?'

In [2]:
string.split()

['Hi,Hello,How', 'Are', 'You?']

In [4]:
string.split(',')

['Hi', 'Hello', 'How Are You?']